# .github/workflows/release.yaml

on:
  push:
    tags: ["*"]

jobs:
  releases-macos-amd64:
    name: Release
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16


      - name: "Build"
        run: |
          pushd ..
          git clone https://github.com/mysteriumnetwork/myst-launcher
          pushd myst-launcher 
          git switch feature/split-model-ui
          popd
          popd
          
          echo "Make gobridge >>>"
          cd gobridge; sh -c ./mk.sh
          cd ..

          echo "Make dmg >>>"
          sh -c ./make_dmg.sh

      - name: Codesign app
        env: 
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
          MACOS_CERTIFICATE_ID: ${{ secrets.MACOS_CERTIFICATE_ID }}
          KEYCHAIN_TMP_PWD: tmppassword
          NOTARIZE_EMAIL: ${{ secrets.NOTARIZE_EMAIL }}
          NOTARIZE_APP_SPEC_PWD: ${{ secrets.NOTARIZE_APP_SPEC_PWD }}

        run: |
          echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12

          security delete-keychain build.keychain || echo ""
          security create-keychain -p $KEYCHAIN_TMP_PWD build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p $KEYCHAIN_TMP_PWD build.keychain

          echo "Import"
          security import certificate.p12 -k build.keychain -P $MACOS_CERTIFICATE_PWD -A 
          # -T /usr/bin/codesign

          echo "Set Key"
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k $KEYCHAIN_TMP_PWD build.keychain

          # echo "Find identity"
          # security find-identity -p codesigning -s build.keychain

          echo "Codesign"
          /usr/bin/codesign --force -s "$MACOS_CERTIFICATE_ID" --timestamp ./build/MysteriumLauncher/Mysterium\ Launcher.app/Contents/MacOS/Mysterium\ Launcher
          echo "Codesign dylib"
          /usr/bin/codesign --force -s "$MACOS_CERTIFICATE_ID" --timestamp -o runtime ./build/MysteriumLauncher/Mysterium\ Launcher.app/Contents/Frameworks/gobridge.dylib

          echo "Codesign whole build"
          /usr/bin/codesign --force -s "$MACOS_CERTIFICATE_ID" --timestamp -o runtime ./build/MysteriumLauncher/Mysterium\ Launcher.app/

          # dmg
          hdiutil create -format UDZO -srcfolder build/MysteriumLauncher mysterium_launcher_macos_amd64.dmg



      - name: Notarize
        env: 
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
          MACOS_CERTIFICATE_ID: ${{ secrets.MACOS_CERTIFICATE_ID }}
          KEYCHAIN_TMP_PWD: tmppassword
          NOTARIZE_EMAIL: ${{ secrets.NOTARIZE_EMAIL }}
          NOTARIZE_APP_SPEC_PWD: ${{ secrets.NOTARIZE_APP_SPEC_PWD }}

          PRIMARY_BUNDLE_ID: com.mysterium.launcher
          APPLE_ID: ${{ secrets.NOTARIZE_EMAIL }}
          APP_SPECIFIC_PASSWORD: ${{ secrets.NOTARIZE_APP_SPEC_PWD }}
          TARGET_BINARY: ./mysterium_launcher_macos_amd64.dmg

        run: |
          # notarize
          #xcrun altool --notarize-app --primary-bundle-id "com.mysterium.launcher" -u $NOTARIZE_EMAIL -p $NOTARIZE_APP_SPEC_PWD -t osx -f ./mysterium_launcher_macos_amd64.dmg
          sh -c ./notarize.sh
          

          #echo Verify
          #/usr/bin/codesign -vvvv ./mysterium_launcher_macos_amd64.dmg

      - name: Upload
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            mysterium_launcher_macos_amd64.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
