# .github/workflows/release.yaml

on:
  push:
    tags: ["*"]

jobs:
  releases-macos-amd64:
    name: Release
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16


      - name: "Build"
        run: |
          pushd ..
          git clone https://github.com/mysteriumnetwork/myst-launcher
          pushd myst-launcher 
          git switch feature/split-model-ui
          popd
          popd
          
          echo "Make gobridge >>>"
          cd gobridge; sh -c ./mk.sh
          cd ..

          echo "Make dmg >>>"
          sh -c ./make_dmg.sh

      - name: Codesign app
        env: 
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
          MACOS_CERTIFICATE_ID: ${{ secrets.MACOS_CERTIFICATE_ID }}
          KEYCHAIN_TMP_PWD: tmppassword
        run: |
          echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12

          security delete-keychain build.keychain || echo ""
          security create-keychain -p $KEYCHAIN_TMP_PWD build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p $KEYCHAIN_TMP_PWD build.keychain

          echo "Import"
          security import certificate.p12 -k build.keychain -P $MACOS_CERTIFICATE_PWD -A #-T /usr/bin/codesign

          echo "Set Key"
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k $KEYCHAIN_TMP_PWD build.keychain

          echo "Find identity"
          security find-identity -v
          security find-identity -p codesigning -s build.keychain

          echo "Codesign"
          /usr/bin/codesign --force -s "$MACOS_CERTIFICATE_ID" ./mysterium_launcher_macos_amd64.dmg
          #/usr/bin/codesign --force -s "$MACOS_CERTIFICATE_ID" ./build/MysteriumLauncher/Mysterium\ Launcher.app/

      - name: Upload
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            mysterium_launcher_macos_amd64.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
